// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi65HD6T8jmDihgq_NgC_ZBDpMjHmo6cs',
    appId: '1:795888310214:web:d351d6e4839eaef05544c7',
    messagingSenderId: '795888310214',
    projectId: 'arcitech-27fec',
    authDomain: 'arcitech-27fec.firebaseapp.com',
    storageBucket: 'arcitech-27fec.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKLDkX9emqcK_XByD1pruV4pnBEYIcP88',
    appId: '1:795888310214:android:a84a3b81a61896685544c7',
    messagingSenderId: '795888310214',
    projectId: 'arcitech-27fec',
    storageBucket: 'arcitech-27fec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAcgLlQb9Ylw15COO0Yq2UuiQLN_fW7lE',
    appId: '1:795888310214:ios:4c65a5305759ed9e5544c7',
    messagingSenderId: '795888310214',
    projectId: 'arcitech-27fec',
    storageBucket: 'arcitech-27fec.appspot.com',
    iosBundleId: 'com.example.arcitech',
  );
}
